# Generated by Django 4.2.5 on 2024-02-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_info',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/'),
        ),
    ]
